export const CLEAR_ADD_STUDENT = 'CLEAR_ADD_STUDENT';
export const ADD_STUDENT_START = 'ADD_STUDENT_START';
export const ADD_STUDENT_SUCCESS = 'ADD_STUDENT_SUCCESS';
export const ADD_STUDENT_FAIL = 'ADD_STUDENT_FAIL';

export const CLEAR_UPDATE_STUDENT = 'CLEAR_UPDATE_STUDENT';
export const UPDATE_STUDENT_START = 'UPDATE_STUDENT_START';
export const UPDATE_STUDENT_SUCCESS = 'UPDATE_STUDENT_SUCCESS';
export const UPDATE_STUDENT_FAIL = 'UPDATE_STUDENT_FAIL';

export const CLEAR_GET_ALL_STUDENTS = 'CLEAR_GET_ALL_STUDENTS';
export const GET_ALL_STUDENTS_START = 'GET_ALL_STUDENTS_START';
export const GET_ALL_STUDENTS_SUCCESS = 'GET_ALL_STUDENTS_SUCCESS';
export const GET_ALL_STUDENTS_FAIL = 'GET_ALL_STUDENTS_FAIL';

