export const CLEAR_ADD_STUDENT = 'CLEAR_ADD_STUDENT';
export const ADD_STUDENT_START = 'ADD_CLIENT_START';
export const ADD_STUDENT_SUCCESS = 'ADD_STUDENT_SUCCESS';
export const ADD_STUDENT_FAIL = 'ADD_STUDENT_FAIL';